### PR TITLE
Enhanced options menu

### PR DESCRIPTION
**Pull request by PaulCombal**
The option menu now uses a separate html file.It allows easier styling, and avoids using "style" attributes.
I made sure these changes would work with smaller resolutions such as 1366x768 by adding "overflow-y: auto" in the CSS, and therefore ensures compatibilty for every user.

Here is what it looks like now, though everything is customizable in CSS, I just created a style in seconds for testing:
image

## IMPORTANT: I did not push the manifest file, because I modifieded it to avoid conflicts. HOWEVER, it needs to be updated! The "web_accessible_properties" item has been modified and should now be set to:
`"web_accessible_resources": [ "night.css", "general.css", "settings.html", "droid-sans.ttf" ]`

Please note that I didnt test it for long, bugs might occur, but for now, it looks rather stable.

Thanks for reviewing

### CODE REVIEW

**Comment by PaulCombal** [comment]
Oh snap, did I just redo what you have done? My extension didnt auto-update, and didnt notice your changes.. I guess you will have to select the best of both worlds.

Such an awkward push tho :/

**Comment by ge-ku** [comment]
Yeah, kinda, I also moved settings into html file. Moving everything about styles into general.css is a great step. Sorry, I can't merge it. :( By the way you don't need to do this:
```
$('head').append($('<link>')
 			.attr("rel","stylesheet")
 			.attr("type","text/css")
 			.attr("href", chrome.extension.getURL('/general.css')));
```
general.css is already injected into the page through manifest (and no need to have it in web_accessible_resources because of that). And I don't think using external font is necessary, standard fonts or fonts loaded by steamgifts are preferred.

Tell me if you want to improve upon my settings.html and moving extension styles into general.css, I'll gladly pull those changes!

**Comment by PaulCombal** [comment]
Ok, thanks for the info, I didn't know that, I'm very new to the browser extension world.
To sum everything up, you just need to merge the whole CSS/HTML separation, right?
Should I delete this pull request, and create a new one with proper HTML5 and CSS only, and using your updated code?

**Comment by ge-ku** [comment]
Yeah, that would be great.

**Pull request closed without merging**
