### PR TITLE
Enhanced Options Menu

### PR DESCRIPTION
**Pull request by PaulCombal**
Following to the previous pull request.
Once again, make sure this doesn't make any bug, and that the manifest file contains all the necessary files. Feel free to change the Arial font which looks very bad. 
Thanks for reviewing.

### CODE REVIEW

**Comment by ge-ku** [comment]
It's already appending settings.html here:
```
$.get(chrome.extension.getURL('/settings.html'), function(settingsDiv){
		 $('body').append(settingsDiv);
...
});
```
This way it's async and doesn't wait for settings to be appended before proceeding with everything else (probably unnoticeable as settings.html is a local file and loads fast but why not 😄 ). Can you remove changes in autoentry.js please?

**Comment by PaulCombal** [comment]
It should be alright now.

**Comment by ge-ku** [comment]
Just tested it myself, my low resolution doesn't let me view whole settings without scrolling 😢 I'll tinker a bit with styles now. I also want these settings to open from chrome://extensions so maybe we should mimic chrome ui style?

**Comment by PaulCombal** [comment]
I just started a template, of course, it's subject to modifications. Modifying the style is up to you, and for the scrollbar issue, try messing around with the `overflow-y` property in #settingsDiv. Make the style your own, it's all just a matter of CSS. I also found a cool looking library for material design controls:
http://ui.lumapps.com/components/button

I assumed that the value 'auto' worked because it worked for me in the chrome "device emulator" thing with 1366x768.

**Comment by ge-ku** [comment]
There is no issue with scrollbar, it's there, I just don't like it since I often open settings to test changes. That library looks amazing but I'd prefer not to use libraries and keep everything simple. And by matching Chrome UI I meant how elements look in chrome://settings/ so if we allow settings.html to be opened in chrome://extensions/ it matches surrounding UI.
P.S. I just moved more styles into general.css (mostly from javascript), don't forget to update this time ;)

**Comment by ge-ku** [comment]
I think I know why your extension did not update itself, there was a "key" line in manifest which made it impossible to install manually and from chrome store simultaneously. I removed it.

**Comment by PaulCombal** [comment]
Alright, when you told me about the chrome UI, for some reason I thought of Google's material Android UI. I'll try to replicate the style chrome currently has. 
And don't worry this time I should be up to date :)

**Comment by ge-ku** [comment]
Thanks! You can add into manifest these lines:
```
   "options_ui": {
      "page": "settings.html"
   },
```
This will make a new button appear:
options

It opens html file (without css or javascript). That's where I took new shadow and overlay color/transparency. Content inside does not however use styles of chrome://resources/css/widgets.css that is used by chromes own settings.

**Comment by PaulCombal** [comment]
Would it be better to make a new HTML file that will embed, with javascript, settings.html in a blank page?
This way, it would be possible to add the metadata tags properly at the beginning of the document, and include the CSS. 
Do you think there is a better way?
Who should start working on this?

**Comment by ge-ku** [comment]
Don't want to edit two files for every change in the future.

About opening in a blank page, here's [what they say](https://developer.chrome.com/extensions/optionsV2) in documentation:
>     // Not recommended; only provided for backwards compatibility,
>     // and will be unsupported in a future version of Chrome (TBD).
>     //"open_in_tab": true
>This is only useful to delay the inevitable deprecation of the old options UI! It will be removed soon, so try not to use it. It will break.

Also there's something I did not notice before:

> chrome_style (boolean) - optional
> If true, a Chrome user agent stylesheet will be applied to your options page. The default value is false, but we recommend you enable it for a consistent UI with Chrome.

May be useful.

You can start with changing settings.html adding all tags needed. In autoentry.js we can append only a part of this file, for example only content of `<body>` tag (or some div we create), while `<head>` would have stuff like jquery library and loading settings into variables. Then we need to move all javascript that handles options into the end of `<body>` (or w/e we decide), creating new .js file most likely.

**Comment by PaulCombal** [comment]
I agree that's a better solution. I'll try doing that when I will have time, or tonight.

**Pull request merged**
