### PR TITLE
added detailed remaining time

### PR DESCRIPTION
**Pull request by vaibhavhrt**
The span showing remaining time on each giveaway now shows a more detailed and accurate remaining time.  
Two lines(200,201) of code added  to change the text of span and one function added at the bottom of file to change time in seconds to d:h:m :s and return a string to be placed inside the span.

### CODE REVIEW

**Comment by ge-ku** [comment]
Seems like it returns wrong values in some cases. For example secToTime(88400) returns "33m:20sec". I think it's because the number of hours in this case is 0 and it skips number of days entirely. Can you fix this?

**Comment by vaibhavhrt** [comment]
Sure i will fix it today. I need to reverse the order conditions in if-else

**Comment by vaibhavhrt** [comment]
Done it should be fixed now. Test it yourself first just to be sure then merge, if there are any other issues let me know.

**Comment by ge-ku** [comment]
Looks good, I'll upload it to the Chrome store when I reach my PC.

**Comment by vaibhavhrt** [comment]
thanks 😺

**Pull request merged**
